### PR TITLE
pos.shape[1] -> pos.shape[0]

### PR DESCRIPTION
**Pull request by madsmpedersen**
Pos has shape [nXYZ, nTB]. 
pos.shape[0] should therefore be used to check if pos contains xy or xyz

### CODE REVIEW

**Comment by rethore** [comment]
Thanks for the pull request. I was actually also working on fixing that bug. I prefer that we keep position array in the form [n,3]. So instead I propose to modify the code in the following way:

```python
    def update_position(self, pos):
        # XYZ position of the rotors
        if pos.shape[1] == 2:
            self.xyz = np.vstack([pos, self.H])
        elif pos.shape[1] == 3:
            self.xyz = pos
        elif pos.shape[0] == 2:
            new_pos = pos.T
            self.xyz = np.vstack([pos, self.H])
        elif pos.shape[0] == 3:
            self.xyz = pos.T
        else:
            raise Exception('Strange position array', pos.shape)
```

Let me know if that's fixing your issue.

**Comment by rethore** [comment]
You can checkout the alternative fix here. 042dd53c7ec1e8adb121c8bfabd8542fa2b5f98a

**Comment by madsmpedersen** [comment]
Will your change work if there is only two or three turbines
Furthermore it conflicts with 

```
self.nWT = self.pos.shape[1]
```
in ```__init__```.

I also prefer [nTB,nXYZ], such that x = pos[:,0], but then it should be changed in the ```__init__```:

**Comment by rethore** [comment]
You are right. I forgot that JP was using the [nXYZ, nTB] arrays in most places in the code.. It's probably going to be a larger fix than I anticipated.

**Comment by rethore** [comment]
dc872bc41d17ba122f1978b2663cb101ca5e17c3: I've made a more broad refactoring of the position arrays (self.pos and self.xyz) within WindFarm.py. It doesn't seem to break anything else. @madsmpedersen: please let me know how that's looking on your side.

**Comment by madsmpedersen** [comment]
Yes it works perfectly fine for me

**Pull request closed without merging**
